@echo off
CLS
SETLOCAL EnableDelayedExpansion

ECHO ====================================================================
ECHO      AUTOMATED SETUP ^& RUN SCRIPT FOR REVIEW CRAWLER (WINDOWS)
ECHO ====================================================================
ECHO This script will fully automate the setup and launch process.
ECHO Please wait, a new window will open to run the application.
ECHO Your web browser will open automatically when setup is complete.
ECHO ====================================================================
ECHO.

REM Lấy đường dẫn gốc của dự án
SET "PROJECT_ROOT=%~dp0"
ECHO [i] Project root directory identified as: %PROJECT_ROOT%
ECHO.

REM --- Bước 1: Quyết định sử dụng Conda hay venv ---
ECHO [?] Checking for Conda installation...
CALL conda --version >nul 2>nul
IF %errorlevel% equ 0 (
    ECHO [i] Conda found! Proceeding with Conda setup.
    GOTO USE_CONDA
) ELSE (
    ECHO [!] Conda not found. Falling back to Python's standard venv.
    GOTO USE_VENV
)


:USE_CONDA
REM ===================== LOGIC CHO CONDA =====================
SET ENV_NAME=review_crawler_env
SET RUN_SCRIPT_PATH="%PROJECT_ROOT%_autogenerated_runner.bat"
ECHO.
ECHO --- Conda Setup ---
ECHO [?] Checking if Conda environment '%ENV_NAME%' exists...
CALL conda env list | findstr /B "%ENV_NAME% " >nul
IF %errorlevel% neq 0 (
    ECHO [+] Conda environment '%ENV_NAME%' not found. Creating it now...
    CALL conda create --name %ENV_NAME% python=3.10 pip -y
) ELSE (
    ECHO [i] Conda environment '%ENV_NAME%' already exists.
)

ECHO [+] Generating the run script for the new environment...

REM --- Tự động tạo ra script thứ hai (Ghi từng dòng một) ---
REM > sẽ tạo file mới và ghi dòng đầu tiên
ECHO @echo off > %RUN_SCRIPT_PATH%
REM >> sẽ nối thêm vào file đã có
ECHO SETLOCAL EnableDelayedExpansion >> %RUN_SCRIPT_PATH%
ECHO ECHO. >> %RUN_SCRIPT_PATH%
ECHO ECHO ========================================================== >> %RUN_SCRIPT_PATH%
ECHO ECHO      ENVIRONMENT '%ENV_NAME%' ACTIVATED SUCCESSFULLY >> %RUN_SCRIPT_PATH%
ECHO ECHO ========================================================== >> %RUN_SCRIPT_PATH%
ECHO ECHO. >> %RUN_SCRIPT_PATH%
ECHO ECHO [+] Installing/updating required packages... >> %RUN_SCRIPT_PATH%
ECHO ECHO -------------------------------------------------------------------- >> %RUN_SCRIPT_PATH%
ECHO CALL python -m pip install -r "%PROJECT_ROOT%requirements.txt" >> %RUN_SCRIPT_PATH%
ECHO IF !errorlevel! neq 0 (ECHO !!! ERROR: Failed to install packages. ^& pause ^& exit /b) >> %RUN_SCRIPT_PATH%
ECHO ECHO -------------------------------------------------------------------- >> %RUN_SCRIPT_PATH%
ECHO ECHO. >> %RUN_SCRIPT_PATH%
ECHO ECHO [+] Starting Scrapyd server in a new background window... >> %RUN_SCRIPT_PATH%
ECHO START "Scrapyd Server" scrapyd >> %RUN_SCRIPT_PATH%
ECHO ECHO [i] Waiting 5 seconds for Scrapyd server to initialize... >> %RUN_SCRIPT_PATH%
ECHO timeout /t 5 /nobreak ^>nul >> %RUN_SCRIPT_PATH%
ECHO IF NOT EXIST "%PROJECT_ROOT%review_crawler\.deployed" ( >> %RUN_SCRIPT_PATH%
ECHO     ECHO [+] Deploying 'review_crawler' project for the first time... >> %RUN_SCRIPT_PATH%
ECHO     cd /D "%PROJECT_ROOT%" >> %RUN_SCRIPT_PATH%
ECHO     CALL scrapyd-deploy >> %RUN_SCRIPT_PATH%
ECHO     IF !errorlevel! equ 0 ( ECHO [i] Deployment successful. Creating flag file. ^& ECHO deployed ^> "%PROJECT_ROOT%review_crawler\.deployed" ) ELSE ( ECHO !!! WARNING: Deployment failed. ) >> %RUN_SCRIPT_PATH%
ECHO ) ELSE ( >> %RUN_SCRIPT_PATH%
ECHO     ECHO [i] Project already deployed. Skipping deployment. >> %RUN_SCRIPT_PATH%
ECHO ) >> %RUN_SCRIPT_PATH%
ECHO ECHO. >> %RUN_SCRIPT_PATH%
ECHO ECHO ========================================================== >> %RUN_SCRIPT_PATH%
ECHO ECHO      SETUP COMPLETE! STARTING THE FASTAPI UI... >> %RUN_SCRIPT_PATH%
ECHO ECHO ========================================================== >> %RUN_SCRIPT_PATH%
ECHO ECHO. >> %RUN_SCRIPT_PATH%
ECHO ECHO [i] Opening the application in your default browser at http://127.0.0.1:8000 >> %RUN_SCRIPT_PATH%
ECHO timeout /t 2 /nobreak ^>nul >> %RUN_SCRIPT_PATH%
ECHO START "" "http://127.0.0.1:8000" >> %RUN_SCRIPT_PATH%
ECHO CALL uvicorn UI_fastapi.app.main:app --host 0.0.0.0 --port 8000 >> %RUN_SCRIPT_PATH%

ECHO [i] Environment is ready. Launching application in a new window...
ECHO [i] This window will close. Please use the new window.
timeout /t 3 >nul

REM --- Khởi chạy Cửa sổ Mới ---
START "Review Crawler App (Conda Env)" cmd /k "conda activate %ENV_NAME% & CALL %RUN_SCRIPT_PATH% & del %RUN_SCRIPT_PATH% & pause & exit"

GOTO END


:USE_VENV
REM ===================== LOGIC CHO VENV (Giữ nguyên) =====================
REM (Luồng Venv không cần thay đổi vì nó không tạo script phụ)
SETLOCAL EnableDelayedExpansion
ECHO.
ECHO --- Venv Setup ---
IF NOT EXIST "%PROJECT_ROOT%venv" (
    ECHO [+] Creating virtual environment 'venv'...
    CALL python -m venv "%PROJECT_ROOT%venv"
    IF !errorlevel! neq 0 ( ECHO !!! ERROR: Failed to create virtual environment. & GOTO FAILED )
)
ECHO [+] Activating venv and running tasks...
CALL "%PROJECT_ROOT%venv\Scripts\activate"
ECHO [+] Installing/updating required packages...
CALL python -m pip install -r "%PROJECT_ROOT%requirements.txt"
IF !errorlevel! neq 0 ( ECHO !!! ERROR: Failed to install packages. & GOTO FAILED )
ECHO [+] Starting Scrapyd server in a new background window...
START "Scrapyd Server" scrapyd
ECHO [i] Waiting 5 seconds...
timeout /t 5 /nobreak >nul
IF NOT EXIST "%PROJECT_ROOT%review_crawler\.deployed" (
    ECHO [+] Deploying 'review_crawler' project...
    cd /D "%PROJECT_ROOT%"
    CALL scrapyd-deploy
    IF !errorlevel! equ 0 ( 
        ECHO deployed > "%PROJECT_ROOT%review_crawler\.deployed"
    )
)
ECHO.
ECHO ==========================================================
ECHO      SETUP COMPLETE! STARTING THE FASTAPI UI...
ECHO ==========================================================
ECHO.
ECHO [i] Opening the application in your default browser at http://127.0.0.1:8000
timeout /t 2 /nobreak >nul
START "" "http://127.0.0.1:8000"
CALL uvicorn UI_fastapi.app.main:app --host 0.0.0.0 --port 8000
GOTO END


:FAILED
ECHO.
ECHO !!! Setup failed. Please check the error messages above.
GOTO END

:END
ECHO.
ECHO --- Main setup script finished. The application is now running. ---
pause